# Site settings
title: Luavis' Dev Story
description: 생계코딩 이야기
email: me@luav.is
timezone: Asia/Seoul
# baseurl: ""  # the subpath of your site, e.g. /blog/
url: "https://b.luavis.kr" # the base hostname & protocol for your site
facebook_username: luavis
github_username:  luavis
nickname: Luavis
designed_by: shydah
designed_by_url: https://www.facebook.com/profile.php?id=100008558805579
since_year: 2015
copyright_year: 2017
include: ["_categories", "_pages"]
permalink: "/:categories/:title"
github: [metadata]
markdown: kramdown
kramdown:
    input: GFM
gems:
    - jekyll-gist
whitelist:
    - jekyll-gist
