# Site settings
title: Luavis' Dev story
description: 소마에서 시작하는 개발질
email: luaviskang@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://b.luavis.kr" # the base hostname & protocol for your site
facebook_username: luavis
github_username:  luavis
nickname: Luavis
copyright_year: 2015
include: ["_categories", "_pages"]
permalink: "/:categories/:title"

markdown: kramdown
