# Site settings
title: Luavis' Dev story
description: 허접의 삽질
email: luaviskang@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://b.luavis.kr" # the base hostname & protocol for your site
facebook_username: luavis
github_username:  luavis
nickname: Luavis
copyright_year: 2016
timezone: 'Asia/Seoul'
include: ["_categories", "_pages"]
permalink: "/:categories/:title"
github: [metadata]
markdown: kramdown
kramdown:
    input: GFM
gems:
    - jekyll-gist
whitelist:
    - jekyll-gist

