# Site settings
title: Luavis' Dev story
description: 생계코딩
email: me@luav.is
timezone: Asia/Seoul
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://b.luavis.kr" # the base hostname & protocol for your site
facebook_username: luavis
github_username:  luavis
nickname: Luavis
copyright_year: 2016
include: ["_categories", "_pages"]
permalink: "/:categories/:title"
github: [metadata]
markdown: kramdown
kramdown:
    input: GFM
gems:
    - jekyll-gist
whitelist:
    - jekyll-gist
